<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_product</name>
   <tag></tag>
   <elementGuidId>ccb5ed27-e062-4675-9c1a-da4edaeebdde</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ad Astra Rocket CompanyAI SolutionsAirbus Defence and Space GmbHAlcatelAlpha Space Test &amp; Research Alliance, LLCARES CorporationASIAstriumAstroboticsAxiom SpaceBarrios Technology, Inc.BigelowBioneticsBIOSERVEBoeingBoeing PayloadsbSpaceBusiness IntegraCalm Technologies, Inc.Cargo Mission ContractCargoV: ATV - ESACargoV: Cargo Dragon - SpaceXCargoV: CRS-2 - Sierra NVCargoV: Cygnus - OrbitalCargoV: HTV - JAXACASISCNESCommonControlled Dynamics IncCrewV: Crew Dragon - SpaceXCrewV: CST100 - BoeingCrewV: Dream Chaser - Sierra NVCrewV: Orion - LMCOCSADes Moines CollegeDLRDoD/JSCDyneticsEADSESTEC/ESAEVA GFEHNU PhotonicsHoneywellIntuitive MachinesISS Li-ion Batteries - PWRJAMSS America, Inc.JAXAJETSJSC-ZRKayser Italia SRLKBR WyleKhrunichevKSC FEPL-3 Cincinnati ElectronicsLASPLockheed MartinMade in SpaceMAPI Flight LeadsMassachusetts Institute of TechnologyMDA (CSA)MDA Space SystemsMEI Technologies, Inc.MSG-IntegrationMuniz EngineeringNANORACKS, LLCNASA ARCNASA GRCNASA GSFCNASA HQNASA JPLNASA JSCNASA KSCNASA LaRCNASA Launch Services ProgramNASA LeRCNASA MSFCNASA WFFNASA WSTFNR-STP PayloadsOceaneeringOdyssey Space ResearchOklahoma State UniversityOrbital PayloadsOrbitecPSRP_ArchiveQinetiQ NAREMIS: BarriosREMIS: BioserveREMIS: BoeingREMIS: CraigREMIS: CSSREMIS: LeidosREMIS: MEIREMIS: OceaneeringREMIS: SNC/OrbitecREMIS: TBEREMIS: Tech MastersREMIS: TechshotREMIS: UTASREMIS: WyleREMIS: ZinRobonaut Mobility UnitRSARSC-EnergiaSabatierSEOPSSilicon Graphics International Corp (SGI)Southwest Research InstituteSpace TangoSTaARS-1STP PayloadsTBE-HoustonTBE-MSFCTechshot, Inc.Terminal Velocity AerospaceThales Alenia SpaceThinkSpace ConsultingTissue Genesis, IncTSISUABUniversity of MaineUniversity of Nebraska Medical CenterUniversity of Nebraska-LincolnUSAFUTC Aerospace SystemsVoxaZIN Technologies, Inc. </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='product']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='tab0']/div/div[3]/div[4]/div/div[2]/div/div/span/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hardware Provider:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='definitions'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsystem/Payload:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span/select</value>
   </webElementXpaths>
</WebElementEntity>
