<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_record_1</name>
   <tag></tag>
   <elementGuidId>34a6a944-d79a-422b-a2f2-1529f84878bb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/show_bug.cgi?id=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui-rec0&quot;)/td[@class=&quot;yui-dt0-col-id yui-dt-col-id&quot;]/div[@class=&quot;yui-dt-liner&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
