import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.logging.KeywordLogger as KeywordLogger
import org.openqa.selenium.Keys as Keys
import org.sikuli.script.Key as Key
import org.sikuli.script.Screen as Screen

//CustomKeywords.'helper.login.LoginHelper.login'()


WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
//WebUI.waitForElementVisible(findTestObject('Object Repository/Page_Enter Record/a_New blank record'),5)
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New blank record'))

return
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_AdAstraRocketCompany'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_AISolutions'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_AirbusDefenceandSpaceGmbH'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Alcatel'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_AlphaSpaceTestResearchAllian'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ARESCorporation'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ASI'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Astrium'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_AxiomSpace'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_BarriosTechnologyInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Bigelow'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Bionetics'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_BIOSERVE'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Boeing'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_BoeingPayloads'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_bSpace'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_BusinessIntegra'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CalmTechnologiesInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoMissionContract'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoVATVESA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoVCargoDragonSpaceX'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoVCRS2SierraNV'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoVCygnusOrbital'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CargoVHTVJAXA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CASIS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CNES'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ControlledDynamicsInc'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CrewVCrewDragonSpaceX'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CrewVCST100Boeing'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CrewVDreamChaserSierraNV'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CrewVOrionLMCO'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_CSA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_DesMoinesCollege'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_DLR'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_DoDJSC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Dynetics'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_EADS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ESTECESA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_EVAGFE'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_HNUPhotonics'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Honeywell'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_IntuitiveMachines'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ISSLiionBatteriesPWR'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_JAMSSAmericaInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_JAXA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_JETS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_JSCZR'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_KayserItaliaSRL'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_KBRWyle'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Khrunichev'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_KSCFEP'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_L3CincinnatiElectronics'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_LASP'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_LockheedMartin'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MadeinSpace'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MAPIFlightLeads'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MassachusettsInstituteofTech'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MDA(CSA)'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MDASpaceSystems'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MEITechnologiesInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MSGIntegration'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_MunizEngineering'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NANORACKSLLC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAARC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAGRC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAGSFC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAHQ'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAJPL'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAJSC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAKSC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASALaRC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASALaunchServicesProgram'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASALeRC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAMSFC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAWFF'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NASAWSTF'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_NRSTPPayloads'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Oceaneering'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_OdysseySpaceResearch'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_OklahomaStateUniversity'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_OrbitalPayloads'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Orbitec'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_PSRP_Archive'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_QinetiQNA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISBarrios'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISBioserve'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISBoeing'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISCraig'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISCSS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISLeidos'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISMEI'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISOceaneering'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISSNCOrbitec'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISTBE'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISTechMasters'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISTechshot'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISUTAS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISWyle'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_REMISZin'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_RobonautMobilityUnit'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_RSA'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Sabatier'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_SEOPS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_SiliconGraphicsInternational'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_SouthwestResearchInstitute'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_SpaceTango'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_STaARS1'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_STPPayloads'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TBEHouston'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TBEMSFC'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TechshotInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TerminalVelocityAerospace'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ThalesAleniaSpace'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ThinkSpaceConsulting'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TissueGenesisInc'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_TSIS'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_UAB'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_UniversityofMaine'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_UniversityofNebraskaLincoln'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_USAF'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_UTCAerospaceSystems'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_Voxa'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_New'))
WebUI.click(findTestObject('Object Repository/Page_Enter Record/a_ZINTechnologiesInc.'))
CustomKeywords.'helper.javascript.JavaScriptHelper.appendBrowserLogs'()


