<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Audit ID</name>
   <tag></tag>
   <elementGuidId>2671b301-63a5-4bec-8da9-ee0266417e6d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cf_audit_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf_audit_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ---1 - BEAM, LIFTING, CORE STAGE ATTACH (CSA) RING - 8U160311-01, 8U160311-02 -2 - STAND, ACCESS, NOZZLE CONE - 8U160315-01 -3 - KIT, INTERNAL ACCESS, AFT SKIRT, PLATFORM ASSY - 8U160327-01, 8U160327-02 -4 - STAND, ACCESS, THERMAL CURTAIN - 8U160316-01 -5 - DOLLY, INSTALLATION, AFT EXIT CONE (AEC) - 8U160308-01 -6 - PLATFORM, INTERNAL ACCESS, FWD SKIRT - 8U160313-03 -7 - BEAM, LIFTING, CORE STAGE ATTACH (CSA) RING - 8U160311-01, 8U160311-02 -8 - STAND, ACCESS, NOZZLE CONE - 8U160315 -9 - KIT, INTERNAL ACCESS, AFT SKIRT, PLATFORM ASSY - 8U160327-01, 8U160327-02 -10 - STAND, ACCESS, THERMAL CURTAIN - 8U160316-01 -11 - Platform, Internal Access, forward Skirt, Ladder - 8U160313-03 -12 - DOLLY, INSTALLATION, AFT EXIT CONE (AEC) - 8U160308-01 -13 - ICAT EGSE &amp; CCLS Rack DIL-0043A - - EURD14 - ICAT EGSE &amp; CCLS Rack DIL-0043B - - EURD15 - ICPS Flight Stage - 1G50001-1 - Flight24 - ORION Transport Pallet - 948MA5050000-501 - GSE31 - Integrated Short Stack Transportation Cover - 948MA5260222-501 - GSE32 - MPCV/Stage Adapter (MSA) Preliminary ADP - - Preliminary / Flight33 - MPCV/Stage Adapter (MSA GSE) - - GSE34 - Pyro Installation Test Set (PITS) - 948EA4070000-503 - GSE42 - EGSE Hatch Installation Test Set (HITS) CEV-T-040069 Rev 000 - 948EA4170000-502 - GSE47 - Launch Vehicle Stage Adapter (LVSA) - - Flight48 - MPCV/Stage Adapter (MSA/OSA) - - Flight63 - Transportation Fixture Spreader Beam / Landing &amp; Recovery GSE - 948MA5020000-503 - GSE64 - Transportation Fixture Hardcover Sling / Landing &amp; Recovery GSE - 948MA5022000-502 - GSE65 - Safing and Recover Post Production Kit - 948MA5674033-501 - GSE66 - SM Post Production Kit - 948MA5673033-501 - GSE67 - CM Post Production Kit - 948MA5672033-501 - GSE </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf_audit_id&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='cf_audit_id']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='tab0']/div/div[8]/div[8]/div[10]/div/div[2]/div/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit ID:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPCA CI ID:'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[10]/div/div[2]/div/div/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
