<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CrewVDreamChaserSierraNV</name>
   <tag></tag>
   <elementGuidId>7c3882a7-bc72-422c-9592-b5eb17d64eee</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>enter_bug.cgi?product=CrewV%3A%20Dream%20Chaser%20-%20Sierra%20NV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CrewV: Dream Chaser ‑ Sierra NV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bugzilla-body&quot;)/div[2]/table[1]/tbody[1]/tr[@class=&quot;program&quot;]/th[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
