package internal

import com.kms.katalon.core.configuration.RunConfiguration
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase

/**
 * This class is generated automatically by Katalon Studio and should not be modified or deleted.
 */
public class GlobalVariable {
     
    /**
     * <p></p>
     */
    public static Object G_image_path
     
    /**
     * <p>Profile WSTFwebPAPER : PASS smoke test
Profile cofr_dev : PASS smoke test
Profile cp_dmm : PASS smoke test
Profile cp_dmm_dev : PASS smoke test
Profile cp_fmea_cil_dev : PASS smoke test
Profile cp_hazard_dev : PASS smoke test
Profile cp_id : PASS smoke test
Profile cp_id_dev : PASS smoke test
Profile cp_inventory : PASS smoke test
Profile cp_inventory_dev : PASS smoke test
Profile cp_praca_dev : PASS smoke test
Profile cpconops : PASS smoke test
Profile cxfmea_cil : PASS smoke test
Profile cxgmip : PASS smoke test
Profile cxhazard : PASS smoke test
Profile cxpraca : PASS smoke test
Profile dex : PASS smoke test
Profile dex_dev : PASS smoke test
Profile ecofr : PASS smoke test
Profile etasksheet : PASS smoke test
Profile etasksheet_dev : PASS smoke test
Profile evat : PASS smoke test
Profile evat_dev : PASS smoke test
Profile fiqs : PASS smoke test
Profile fiqs_dev : PASS smoke test
Profile gmip_dev : PASS smoke test
Profile human_capital_dev : PASS smoke test
Profile iss_fmea : PASS smoke test
Profile iss_fmea_dev : PASS smoke test
Profile iss_hazard : PASS smoke test
Profile iss_hazard_dev : PASS smoke test
Profile iss_part : PASS smoke test
Profile iss_part_dev : PASS smoke test
Profile mcard : PASS smoke test
Profile mcard_dev : PASS smoke test
Profile ocad : PASS smoke test
Profile ocad_dev : PASS smoke test
Profile practis : PASS smoke test
Profile practis_dev : PASS smoke test
Profile react_cp_hazard_dev : PASS smoke test
Profile ssma : Production site !!!
Profile wstf_dev : PASS smoke test</p>
     */
    public static Object G_MAKE_MAS_url
     
    /**
     * <p></p>
     */
    public static Object G_timeout
     
    /**
     * <p></p>
     */
    public static Object G_wait_s
     
    /**
     * <p></p>
     */
    public static Object G_wait_m
     
    /**
     * <p></p>
     */
    public static Object G_wait_l
     
    /**
     * <p></p>
     */
    public static Object smartcard_login_button
     
    /**
     * <p></p>
     */
    public static Object G_userPin
     
    /**
     * <p></p>
     */
    public static Object G_dagger_server_url
     
    /**
     * <p></p>
     */
    public static Object G_git_hash_ver
     
    /**
     * <p></p>
     */
    public static Object G_permitted_browser
     
    /**
     * <p></p>
     */
    public static Object G_tag_ver
     
    /**
     * <p></p>
     */
    public static Object userPin2
     
    /**
     * <p></p>
     */
    public static Object userPin3
     
    /**
     * <p></p>
     */
    public static Object cp_oms_dev
     
    /**
     * <p></p>
     */
    public static Object cp_hazard_dev
     
    /**
     * <p></p>
     */
    public static Object cp_lms_dev
     
    /**
     * <p>Profile default : CP-Hazard, CP-OMS
Profile WSTFwebPAPER : CP-Hazard, CP-OMS
Profile arc_praca : CP-Hazard, CP-OMS
Profile arc_praca_dev : CP-Hazard, CP-OMS
Profile arcjetdb : CP-Hazard, CP-OMS
Profile cofr_dev : CP-Hazard, CP-OMS
Profile cp_dmm : CP-Hazard, CP-OMS
Profile cp_dmm_dev : CP-Hazard, CP-OMS
Profile cp_fmea_cil_dev : CP-Hazard, CP-OMS
Profile cp_hazard_dev : CP-Hazard, CP-OMS
Profile cp_id : CP-Hazard, CP-OMS
Profile cp_id_dev : CP-Hazard, CP-OMS
Profile cp_inventory : CP-Hazard, CP-OMS
Profile cp_inventory_dev : CP-Hazard, CP-OMS
Profile cp_lms : CP-Hazard, CP-OMS
Profile cp_lms_dev : CP-Hazard, CP-OMS
Profile cp_oms : CP-Hazard, CP-OMS
Profile cp_oms_dev : CP-Hazard, CP-OMS
Profile cp_praca_dev : CP-Hazard, CP-OMS
Profile cpconops : CP-Hazard, CP-OMS
Profile cxfmea_cil : CP-Hazard, CP-OMS
Profile cxgmip : CP-Hazard, CP-OMS
Profile cxhazard : CP-Hazard, CP-OMS
Profile cxpraca : CP-Hazard, CP-OMS
Profile dex : CP-Hazard, CP-OMS
Profile dex_dev : CP-Hazard, CP-OMS
Profile doctree : CP-Hazard, CP-OMS
Profile doctree_dev : CP-Hazard, CP-OMS
Profile ecofr : CP-Hazard, CP-OMS
Profile etasksheet : CP-Hazard, CP-OMS
Profile etasksheet_dev : CP-Hazard, CP-OMS
Profile evat : CP-Hazard, CP-OMS
Profile evat_dev : CP-Hazard, CP-OMS
Profile fiqs : CP-Hazard, CP-OMS
Profile fiqs_dev : CP-Hazard, CP-OMS
Profile gmip_dev : CP-Hazard, CP-OMS
Profile human_capital_dev : CP-Hazard, CP-OMS
Profile iss_fmea : CP-Hazard, CP-OMS
Profile iss_fmea_dev : CP-Hazard, CP-OMS
Profile iss_hazard : CP-Hazard, CP-OMS
Profile iss_hazard_dev : CP-Hazard, CP-OMS
Profile iss_part : CP-Hazard, CP-OMS
Profile iss_part_dev : CP-Hazard, CP-OMS
Profile krampmasenstein_dev : CP-Hazard, CP-OMS
Profile mcard : CP-Hazard, CP-OMS
Profile mcard_dev : CP-Hazard, CP-OMS
Profile ocad : CP-Hazard, CP-OMS
Profile ocad_dev : CP-Hazard, CP-OMS
Profile pracaBugs : CP-Hazard, CP-OMS
Profile practis : CP-Hazard, CP-OMS
Profile practis_dev : CP-Hazard, CP-OMS
Profile react_arcjetdb_dev : CP-Hazard, CP-OMS
Profile react_cp_hazard_dev : CP-Hazard, CP-OMS
Profile react_iss_hazard_dev : CP-Hazard, CP-OMS
Profile rheo : CP-Hazard, CP-OMS
Profile rheo_dev_qa : CP-Hazard, CP-OMS
Profile rheo_stage : CP-Hazard, CP-OMS
Profile sims : CP-Hazard, CP-OMS
Profile sims_dev : CP-Hazard, CP-OMS
Profile ssma : CP-Hazard, CP-OMS
Profile ssma_dev : CP-Hazard, CP-OMS
Profile stafftrac : CP-Hazard, CP-OMS
Profile wstf_dev : CP-Hazard, CP-OMS</p>
     */
    public static Object G_MAKE_MAS_title
     
    /**
     * <p>Profile ocad : need a record to have snapshots already to test diff report
</p>
     */
    public static Object recordName1
     
    /**
     * <p></p>
     */
    public static Object recordName2
     
    /**
     * <p></p>
     */
    public static Object search_term
     
    /**
     * <p></p>
     */
    public static Object search_keyWord
     
    /**
     * <p></p>
     */
    public static Object signatureDisabled
     
    /**
     * <p></p>
     */
    public static Object addNewRecord
     
    /**
     * <p></p>
     */
    public static Object bad_browser_blurb_message
     
    /**
     * <p></p>
     */
    public static Object allowedBrowsers
     
    /**
     * <p></p>
     */
    public static Object savedSearchName
     

    static {
        def allVariables = [:]        
        allVariables.put('default', ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_hazard_csn/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('WSTFwebPAPER', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/WSTFwebPAPER', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '112229', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('arc_praca', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/ARC-PRACA/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '2116', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('arc_praca_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/arc_praca_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '2155', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('arcjetdb', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/arcjetdb/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '3468', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cofr_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cofr_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '89', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_dmm', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/cpdmm', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP DMM', 'recordName1' : '228', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : false, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_dmm_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_dmm_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[7]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP DMM', 'recordName1' : '228', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : false, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_fmea_cil_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_fmea_cil_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[7]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '73432', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_hazard_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_hazard_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '7594', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_id', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/cpid/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '961', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_id_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_id_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_inventory', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/Inventory', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '764', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_inventory_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_inventory_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_lms', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cplms.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'LMS', 'recordName1' : '1', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_lms_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'LMS', 'recordName1' : '1', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_oms', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cpoms.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-OMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_oms_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-OMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cp_praca_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_praca_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[7]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cpconops', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/cpconops', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '7594', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cxfmea_cil', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cxfmea-cil.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '73432', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cxgmip', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cxgmip.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '4638', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cxhazard', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cxhazard.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '7594', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('cxpraca', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://cxpraca.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('dex', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/dex/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'DEx', 'recordName1' : '1', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('dex_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/dex_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'DEx', 'recordName1' : '1', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('doctree', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/doctree', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('doctree_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/doctree_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('ecofr', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://ecofr.nasa.gov', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '89', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('etasksheet', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/etasksheet/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'ARC JET', 'recordName1' : 'AHF 307', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('etasksheet_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/etasksheet_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'ARC JET', 'recordName1' : 'AHF 307', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('evat', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/evat_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[567]|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('evat_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/evat_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[567]|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('fiqs', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/FIQS', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '664', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('fiqs_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/fiqs_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '664', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('gmip_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/gmip_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '4639', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('human_capital_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/human_capital_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'StaffTrac', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_fmea', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://fmea.iss.nasa.gov', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'ISS FMEA/CIL', 'recordName1' : 'Test title', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_fmea_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/iss_fmea_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'ISS FMEA/CIL', 'recordName1' : 'Test title', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_hazard', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://hazard.iss.nasa.gov', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '14848', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_hazard_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/iss_hazard_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '14848', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_part', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://part.iss.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('iss_part_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/iss_part_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('krampmasenstein_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/krampmasenstein_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '7113', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('mcard', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/mcard', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'MCaRD', 'recordName1' : '10', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('mcard_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/mcard_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'MCaRD', 'recordName1' : '10', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('ocad', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://ocad.iss.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'OCAD', 'recordName1' : '122620', 'recordName2' : '122620', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : false, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('ocad_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/ocad_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'OCAD', 'recordName1' : 'test_automation_record', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('pracaBugs', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/pracaBugs', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '936', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('practis', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/PRACTIS', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('practis_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/practis_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('react_arcjetdb_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_arcjetdb_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '3468', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('react_cp_hazard_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '7633', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('react_iss_hazard_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_iss_hazard_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server-vmdb/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'ISS Hazard', 'recordName1' : '14848', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('rheo', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/rheo', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://cptrace.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('rheo_dev_qa', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-stage.nas.nasa.gov/MAKE-MAS/mas/rheo_dev_qa/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('rheo_stage', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/rheo_stage_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : 'https://dig-it-dev.nas.nasa.gov/dig_it-server/services/', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('sims', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/sims', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SIMS', 'recordName1' : '109', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : false, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('sims_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/sims_dev/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|MSIE 9|Trident/[567]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : 'test_automation_record', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('ssma', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas.nasa.gov/ssma/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[567]|Chrome', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SSMA', 'recordName1' : '10', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : false, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('ssma_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/ssma_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'SSMA', 'recordName1' : 'test_automation_record', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        allVariables.put('stafftrac', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://stafftrac.arc.nasa.gov/', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : 'debf133', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[78]|Chrome|Safari', 'G_tag_ver' : '21303', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '488', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox', 'Safari'], 'savedSearchName' : 'joe_search'])
        allVariables.put('wstf_dev', allVariables['default'] + ['G_image_path' : '/Users/jcfu/Katalon Studio/HCI_Group/cp_hazard.sikuli/', 'G_MAKE_MAS_url' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/wstf_dev', 'G_timeout' : 30, 'G_wait_s' : 2, 'G_wait_m' : 5, 'G_wait_l' : 10, 'smartcard_login_button' : 'G_image_path+\'smartcard_login_button.png\'', 'G_userPin' : '10051965', 'G_dagger_server_url' : '', 'G_git_hash_ver' : '48654b9', 'G_permitted_browser' : 'Firefox/(?![123456789]\\.)|Trident/[5678]|Chrome', 'G_tag_ver' : 'develop HEAD (21372)', 'userPin2' : '108676523', 'userPin3' : '10062016', 'cp_oms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_oms_dev/', 'cp_hazard_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/react_cp_hazard_dev/', 'cp_lms_dev' : 'https://mas-dev.nas.nasa.gov/MAKE-MAS/mas/cp_lms_dev/', 'G_MAKE_MAS_title' : 'CP-Hazard', 'recordName1' : '111948', 'recordName2' : '', 'search_term' : '', 'search_keyWord' : '', 'signatureDisabled' : false, 'addNewRecord' : true, 'bad_browser_blurb_message' : '', 'allowedBrowsers' : ['Explorer', 'Chrome', 'Firefox'], 'savedSearchName' : 'joe_search'])
        
        String profileName = RunConfiguration.getExecutionProfile()
        
        def selectedVariables = allVariables[profileName]
        G_image_path = selectedVariables['G_image_path']
        G_MAKE_MAS_url = selectedVariables['G_MAKE_MAS_url']
        G_timeout = selectedVariables['G_timeout']
        G_wait_s = selectedVariables['G_wait_s']
        G_wait_m = selectedVariables['G_wait_m']
        G_wait_l = selectedVariables['G_wait_l']
        smartcard_login_button = selectedVariables['smartcard_login_button']
        G_userPin = selectedVariables['G_userPin']
        G_dagger_server_url = selectedVariables['G_dagger_server_url']
        G_git_hash_ver = selectedVariables['G_git_hash_ver']
        G_permitted_browser = selectedVariables['G_permitted_browser']
        G_tag_ver = selectedVariables['G_tag_ver']
        userPin2 = selectedVariables['userPin2']
        userPin3 = selectedVariables['userPin3']
        cp_oms_dev = selectedVariables['cp_oms_dev']
        cp_hazard_dev = selectedVariables['cp_hazard_dev']
        cp_lms_dev = selectedVariables['cp_lms_dev']
        G_MAKE_MAS_title = selectedVariables['G_MAKE_MAS_title']
        recordName1 = selectedVariables['recordName1']
        recordName2 = selectedVariables['recordName2']
        search_term = selectedVariables['search_term']
        search_keyWord = selectedVariables['search_keyWord']
        signatureDisabled = selectedVariables['signatureDisabled']
        addNewRecord = selectedVariables['addNewRecord']
        bad_browser_blurb_message = selectedVariables['bad_browser_blurb_message']
        allowedBrowsers = selectedVariables['allowedBrowsers']
        savedSearchName = selectedVariables['savedSearchName']
        
    }
}
