<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PRNT-2</name>
   <tag></tag>
   <elementGuidId>4ab51f26-43af-47e1-9c14-44d2f0a7a86a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fieldLink_dataCard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRNT-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expandedOutDiv_cfgr_g2g_child_88&quot;)/div[@class=&quot;dataCardDiv&quot;]/div[2]/div[@class=&quot;column&quot;]/div[@class=&quot;dataCardOuterDiv X___&quot;]/div[@class=&quot;dataCard&quot;]/div[@class=&quot;dataCardHeader&quot;]/div[@class=&quot;dataCardHeaderRight&quot;]/div[@class=&quot;dataCardHeaderLink&quot;]/a[1]/span[1]/span[@class=&quot;fieldLink_dataCard&quot;]</value>
   </webElementProperties>
</WebElementEntity>
