<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_trash</name>
   <tag></tag>
   <elementGuidId>fdec3157-c44e-49ac-8c6b-0ac7cdff72c6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;external_link_row790&quot;)/div[@class=&quot;recordLinkCell recordRightCellBtm recordRightCellBtm_XFMEA&quot;]/div[2]/div[@class=&quot;trash&quot;]</value>
   </webElementProperties>
</WebElementEntity>
