<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Altair ActionsAres IAres I</name>
   <tag></tag>
   <elementGuidId>8ff3cc56-6c41-43a1-9ab1-10fe5461771b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nasa-ms</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Altair ActionsAres IAres I ActionsCSERP ActionsCSSSCxOrionEGS HazardsES Cause TreeES Integrated ActionES Integrated WatchEVA ActionsExploration Systems Integrated CausesGround OperationsGround Ops ActionsMission OperationsMission Ops ActionsOrion AA-2 Gnd HazardsOrion ActionsOrion GFE HazardsOrion GFE Safety Data PackageOrion MPCV HazardsOther ActionsSE+ISE+I ActionsSLS Green RunSLS IATF HazardSLS Integrated ActionSLS Integrated CauseSLS Integrated HazardSLS Integrated WatchSLS Modal TestsSLS: BoosterSLS: Core StageSLS: Exploration Upper StageSLS: Integrated Shared VolumeSLS: ISPESLS: ISPE-EM-1 Secondary PayloadsSLS: ISPE-GSESLS: ISPE-ICPSSLS: ISPE-LVSASLS: ISPE-MSASLS: ISPE-PayloadsSLS: ISPE-PLASLS: ISPE-USA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)</value>
   </webElementProperties>
</WebElementEntity>
