<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRNT-8  GROUP_PRNT-8</name>
   <tag></tag>
   <elementGuidId>a58669ce-3d71-4d7a-ad15-1d05c9c52805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'groupTitleLabel_rowTitle' and (contains(text(), 'PRNT-8:  GROUP_PRNT-8') or contains(., 'PRNT-8:  GROUP_PRNT-8'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>groupTitleLabel_rowTitle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GROUP_PRNT-8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsedSpan_133&quot;)/div[1]/div[@class=&quot;groupTitleLabel_rowTitle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
