<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRNT-7  GROUP_PRNT-7</name>
   <tag></tag>
   <elementGuidId>1d7c6dd4-6812-4ae6-a186-fa9176272d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'groupTitleLabel_rowTitle' and (contains(text(), 'PRNT-7:  GROUP_PRNT-7') or contains(., 'PRNT-7:  GROUP_PRNT-7'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>groupTitleLabel_rowTitle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GROUP_PRNT-7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsedSpan_132&quot;)/div[1]/div[@class=&quot;groupTitleLabel_rowTitle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
