<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMsg_sqlQuerySQLParser</name>
   <tag></tag>
   <elementGuidId>b27704bd-2627-4a00-80c6-932f69c550e7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sqlQuery:SQLParser.parse: malformed sql</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf_rh_part_number_NEW_ROW_1_overlay_search&quot;)/div[@class=&quot;overlaySearch_div&quot;]/div[@class=&quot;digIt_error&quot;]/span[@class=&quot;digIt_error_text&quot;]/em[1]</value>
   </webElementProperties>
</WebElementEntity>
