<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ctl-8</name>
   <tag></tag>
   <elementGuidId>3a3f9446-b2e3-46f8-996a-37baafa1496e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cfgr_Controls_row_13686_collapsed_display_area_content&quot;]/span[(contains(text(), 'Ctl-8.') or contains(., 'Ctl-8.'))]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='cfgr_Controls_row_13686_collapsed_display_area_content']/span[(contains(text(), 'Ctl-8.') or contains(., 'Ctl-8.'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g_title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ctl-8.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='cfgr_Controls_row_13686_collapsed_display_area_content']/span[(contains(text(), 'Ctl-8.') or contains(., 'Ctl-8.'))]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
</WebElementEntity>
